### ISSUE TITLE
Failing to connect to websocket in 3.80

### ISSUE THREAD

**Issue by underscorejasiu** [kesteraernoudt/pydobiss#2]
After updating dobiss to 3.80 and ha integration to 1.9 it fails to establish websocket connection:

`2024-11-07 18:19:54.756 DEBUG (MainThread) [dobissapi.dobissapi] registering for websocket connection
2024-11-07 18:19:54.761 ERROR (MainThread) [dobissapi.dobissapi] Failed to connect, waiting a bit before retrying: ClientResponseError(RequestInfo(url=URL('ws://192.168.0.25/sockets/api'), method='GET', headers=<CIMultiDictProxy('Host': '192.168.0.25', 'Authorization': 'Bearer <access token>', 'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Sec-WebSocket-Version': '13', 'Sec-WebSocket-Key': '7Vm4ASxEamKpLU4URYk1Fw==', 'Sec-WebSocket-Protocol': 'wamp', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Python/3.12 aiohttp/3.10.10')>, real_url=URL('ws://192.168.0.25/sockets/api')), (), status=502, message='Bad Gateway', headers=<CIMultiDictProxy('Server': 'nginx/1.18.0', 'Date': 'Thu, 07 Nov 2024 17:19:54 GMT', 'Content-Type': 'text/html', 'Content-Length': '494', 'Connection': 'keep-alive', 'Etag': '"65dcb6dd-1ee"')>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dobissapi/dobissapi.py", line 868, in listen_for_dobiss
    ws = await self._session.ws_connect(self._ws_url, protocols=["wamp"], headers=headers)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 937, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 793, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url='ws://192.168.0.25/sockets/api'
`

due to that none of states of entities is correct (and based on that rest of triggers dont work correctly). 
Side effect is basically killing websocket service of dobiss nxt

**Comment by underscorejasiu** [comment]
issue is on nxt side - closing

**Comment by kesteraernoudt** [comment]
FYI: this issue came up here: https://github.com/kesteraernoudt/dobiss/issues/202
There is a workaround in there. Basically there was an issue with the initial dobiss nxt update, and that caused this incompatibility to be worse...
